---
title: "Springboard Capstone Project Proposal"
author: "Edward Yu"
date: "January 9, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Autism Spectrum Disorder Screening: Regression Models and ML Predictions


### Problem Description and Goals
Autism Spectrum Disorder is name given to a range of neurodevelopmental disorders. Individuals diagnosed with autism exhibit two types of behavioral problems: problems in social communication and interaction, and display restrictive, repetitive patterns of behaviors and interests. ASD can be diagnosed as early as 18 months; it can be reliably diagnosed typically by the age of 2. Clinicians face several difficulties in properly diagnosing ASD such as differentiating it among other pervasive developmental disorders, intellectual disabilities unrelated to development disorders, language disorders, ADHD, and anxiety. Considering the difficulties in properly diagnosing ASD, evidence based assessments have been published by the American Academy of Neurology and the American Academy of Child and Adolescent Pschiatry. These assessments are carried out by general practitioners (i.e. level 1 screening) and for children who fail those assessments are then evaluated by experienced clinicians (i.e. level 2 screening). 

The project's goal is to apply statistical methods and machine learning techniques in order to: 

1. Classify whether individuals have ASD based on significant features.
2. Determine which features are more significant than others in classifying ASD positive individuals 
3. Compare models with differing covariates and assess strengths and weaknesses of each model.
4. Finalized project will include R code, written paper, and slide/deck of findings.

### Potential Project Impact
The results of the project can be used to increase the speed, accuracy, sensitivity, and specificity of ASD diagnosis. Novel insights from this project can be used to amend current screening assessments under the DSM-IV definitions of ASD to transition to the newly imposed critiera of ASD under the revised DSM-V. The DSM-5 is the Diagnostic and Statistical Manual of Mental Disorders, the taxonomic and diagnostic tool published by the American Psychiatric Association (APA), which in the united States is universally recognized as the authority for psychiatric diagnoses. Potential parties of interest are the following: general physicians performing level 1 screening, clinicians performing level 2 screening, hospitals and healthcare providers with interest in staying abreast of ASD diagnoses and protocol, and families interested in preliminary ASD risk assessment of their child (via app asking them a series of questions determinant of ASD). 


### Autism Dataset of Research
Data was acquired from UCI and sourced from: 

Fadi Fayez Thabtah  
Department of Digital Technology  
Manukau Institute of Technology,  
Auckland, New Zealand  
[fadi.fayez@manukau.ac.nz](fadi.fayez@manukau.ac.nz)  
[UCI Autism Screening Adult Dataset Link](https://archive.ics.uci.edu/ml/datasets/Autism+Screening+Adult)


